### Send GET request
GET http://localhost:8080/api/v1/car
Accept: application/json

### Send POST request with json body
POST http://localhost:8080/api/v1/car
Content-Type: application/json

{
  "name": "someName"
}

### Send POST to reserve a car
POST http://localhost:8080/api/v1/reservation
Content-Type: application/json

{
  "carId": "22222222-2222-2222-2222-222222222222",
  "startTime": "2025-12-01T10:00:00Z",
  "endTime": "2025-12-01T16:00:00Z"
}