/**
 * NoyStack API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * RFC 7807 Problem Details
 */
export interface ProblemDetail { 
    title: string;
    status: number;
    detail?: string;
}

