/**
 * NoyStack API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ReservationResponseDto { 
    carId: string;
    startTime: string;
    endTime: string;
    id?: string;
    userId?: string;
}

