/**
 * NoyStack API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CarDto } from '../model/models';
import { CarResponseDto } from '../model/models';
import { ProblemDetail } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CarServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Delete a car by ID.
     * 
     * @endpoint delete /api/v1/car/{carId}
     * @param carId 
     */
    deleteCar(carId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get a car by ID.
     * 
     * @endpoint get /api/v1/car/{carId}
     * @param carId 
     */
    getCarById(carId: string, extraHttpRequestParams?: any): Observable<CarResponseDto>;

    /**
     * Returns a list of cars.
     * 
     * @endpoint get /api/v1/car
     */
    getCars(extraHttpRequestParams?: any): Observable<Array<CarResponseDto>>;

    /**
     * Create a new car.
     * 
     * @endpoint post /api/v1/car
     * @param carDto car object to create
     */
    postCar(carDto: CarDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Update a car by ID.
     * 
     * @endpoint put /api/v1/car/{carId}
     * @param carId 
     * @param carDto car object to update
     */
    putCar(carId: string, carDto: CarDto, extraHttpRequestParams?: any): Observable<CarResponseDto>;

}
