/**
 * NoyStack API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ReservationDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ReservationServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Returns a list of reservations.
     * 
     * @endpoint get /api/v1/reservation
     * @param userId Filter reservations by user ID
     * @param carId Filter reservations by car ID
     * @param startDate Filter reservations starting from this date
     * @param endDate Filter reservations ending by this date
     */
    getReservations(userId?: string, carId?: string, startDate?: string, endDate?: string, extraHttpRequestParams?: any): Observable<Array<ReservationDto>>;

}
