/**
 * NoyStack API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ProblemDetail } from '../model/models';
import { ReservationDto } from '../model/models';
import { ReservationResponseDto } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface ReservationServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * Delete a reservation by ID.
     * 
     * @endpoint delete /api/v1/reservation/{reservationId}
     * @param reservationId 
     */
    deleteReservation(reservationId: string, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Get a reservation by ID.
     * 
     * @endpoint get /api/v1/reservation/{reservationId}
     * @param reservationId 
     */
    getReservationById(reservationId: string, extraHttpRequestParams?: any): Observable<ReservationResponseDto>;

    /**
     * Returns a list of reservations.
     * 
     * @endpoint get /api/v1/reservation
     * @param userId Filter reservations by user ID
     * @param carId Filter reservations by car ID
     * @param startDate Filter reservations starting from this date
     * @param endDate Filter reservations ending by this date
     */
    getReservations(userId?: string, carId?: string, startDate?: string, endDate?: string, extraHttpRequestParams?: any): Observable<Array<ReservationResponseDto>>;

    /**
     * Create a new reservation.
     * 
     * @endpoint post /api/v1/reservation
     * @param reservationDto reservation object to create
     */
    postReservation(reservationDto?: ReservationDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * Update a reservation by ID.
     * 
     * @endpoint put /api/v1/reservation/{reservationId}
     * @param reservationId 
     * @param reservationDto reservation object to update
     */
    putReservation(reservationId: string, reservationDto: ReservationDto, extraHttpRequestParams?: any): Observable<ReservationResponseDto>;

}
